### ISSUE TITLE
lintSource message _node is null

### ISSUE THREAD

**Issue by lishu** [birjolaxew/svglint#23]
I try use this at JS API.
But like title, The most important attribute as lint is missing.

**Comment by ericcornelissen** [comment]
@lishu could you elaborate on what is missing? Is this package not working for you at all or is it missing a feature? A working example would be very helpful in order to understand your issue better.

**Comment by lishu** [comment]
It was a long time ago, and I wanted to include real-time lint for my vscode extension, and when I tried to use your library, I found that I couldn't get the wrong rank information when I used strings for svg content, and I gave up.

**Comment by ericcornelissen** [comment]
Thanks for the context @lishu. I'm still interested in getting to the bottom of this so if you could provide more details on how you are/were using this package that would be very helpful. But if you don't intend on using this package anymore I understand if you don't want to spend time reproducing the problem just for this issue, in which case feel free to close this.
