### ISSUE TITLE
Consider replacing meow dependency

### ISSUE THREAD

**Issue by birjolaxew** [birjolaxew/svglint#34]
As mentioned [here](https://github.com/birjolaxew/svglint/issues/31#issuecomment-860077119), the `meow` dependency has a transitive dependency vulnerability. It's also gone through a number of breaking changes -- most notably [it is now incompatible with CommonJS](https://gist.github.com/sindresorhus/a39789f98801d908bbc7ff3ecc99d99c). It also now requires NodeJS 12+.

We could choose to rewrite the CLI using ESM instead of CommonJS, but the NodeJS system requirement would still be a breaking change (and a largely unnecessary one at that). We could alternatively choose to replace `meow` with another CLI helper library.

**Comment by ericcornelissen** [comment]
What actually is the currently targetted minimum NodeJS version? [The project manifest](https://github.com/birjolaxew/svglint/blob/master/package.json) doesn't specify anything. :thinking: 

My vote would go towards upgrading the codebase to use ES Modules and providing backwards compatibility to the API for older node version by including a transpiled CommonJS version of the package, creating in a prepublish step. I'm not sure how we could go about providing both an ESM and CJS "binary", but I'd say that with v12 being the oldest LTS NodeJS, we can generally expect developers to be using at least v12 on the CLI.

I'm in favor of upgrading as:

- it future proofs the code (in particular with respect to dependencies switching to ESM),
- it simplifies resolving this issue (as well as #36 and possibly others in the future), and
- backwards compatibility can be provided by transpiling the source code.

That being said, changing the CLI helper library shouldn't be too hard either. @birjolaxew, do you feel strongly that we should stick with CommonJS?

**Comment by birjolaxew** [comment]
@ericcornelissen Sorry about the slow response. I have been without a computer for a bit.

That plan sounds good to me. I would generally prefer not dropping support for a previously supported Node version (with "supported" meaning "works", since it's all been a bit non explicit), but if we're going to explicitly state a minimum supported version (which I agree we should) then we might as well use the opportunity to align it with e.g. the LTS schedule. I'm fine with bumping to v12. Converting to ES modules would definitely also be an upgrade.
