### ISSUE TITLE
SVGLint endless loop

### ISSUE THREAD

**Issue by ericcornelissen** [birjolaxew/svglint#5]
SVGLint seems to get stuck on [this SVG](https://github.com/simple-icons/simple-icons/blob/ddd022528a9a0a54ebf78e594f4603ba9a19cf54/icons/codesandbox.svg?short_path=5a77d37) in the [Travis CI build](https://travis-ci.org/simple-icons/simple-icons/jobs/486175810) for [simple-icons#1184](https://github.com/simple-icons/simple-icons/pull/1184) (I restarted the build 3 times).

> No output has been received in the last 10m0s, this potentially indicates a stalled build or something wrong with the build itself.

**Comment by sambrannon** [comment]
This might be happening because of the empty line at the start of the file.

I am testing out svglint for a project and came across this same issue. Can reproduce the issue by adding an empty line 1. Removing the empty line allows the build to pass. Hope that helps.

**Comment by birjolaxew** [comment]
This should be fixed in version 1.0.5, which has just been pushed to NPM.
