### ISSUE TITLE
Allow to disable color in output

### ISSUE THREAD

**Issue by mondeja** [birjolaxew/svglint#50]
Currently, there is no way to disable color with SVGLint. This is a proposal for introducing a check for the presence of a `NO_COLOR` environment variable that, when present (regardless of its value), prevents the addition of ANSI color.

See the informal specification https://no-color.org

**Comment by ericcornelissen** [comment]
Based on [Command Line Interface Guidelines](https://clig.dev/) we could also consider the following (some of which are also mentioned on the [no-color website](https://no-color.org/)):

- Disabling colors when the output terminal is not a TTY ([example implementation](https://github.com/stryker-mutator/stryker-js/blob/67ee8976cde7ea53664238276f001f25aec50e71/packages/core/src/reporters/broadcast-reporter.ts#L28)).
- The `TERM` environment variable has the value `dumb`.

And, with lower priority, also:

- An `SVGLINT_NO_COLOR` environment variable that's similar to `NO_COLOR` but only for SVGLint.
- A `--no-color` CLI flag.
- A `color` option in the config file that's either `true` or `false`.
